version: '3'

services:
  db: 
   image: postgres
   restart: always
   container_name: pruebaDB
   environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_DB: ${DB_NAME}
   ports: 
    - 3032:5432 
   volumes: 
    - ./data:/var/lib/postgresql/data
